### ISSUE TITLE
Error: EADDRINUSE, Address already in use

### ISSUE THREAD

**Issue by crittermike** [dantebronto/picard#16]
I'm now getting this error upon running node app.js for any of the example apps: 

```
mcrittenden@freshbook:~/Desktop/picard/examples/basic$ node app.js 

node.js:68
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:1018:5)
    at net.js:989:14
    at Object.lookup (dns.js:126:33)
    at Server.listen (net.js:983:20)
    at Object.start (/home/mcrittenden/Desktop/picard/lib/picard/server.js:14:7)
    at Object.<anonymous> (/home/mcrittenden/Desktop/picard/examples/basic/app.js:46:8)
    at Module._compile (node.js:423:30)
    at Object..js (node.js:429:14)
    at Module.load (node.js:355:35)
    at Array.<anonymous> (node.js:443:26)
```

**Comment by crittermike** [comment]
Oh geez, this is my fault, I'm an idiot. Closing...

**Comment by crittermike** [comment]
.

**Comment by dantebronto** [comment]
Haha, no worries. I appreciate you taking the time to file issues.

**Comment by kfa1983** [comment]
And could you please share how you solved it??? xD Thanks

**Comment by crittermike** [comment]
kfa1983 I was getting the error because I was already running "node app.js" in another terminal window. You have to make sure you're only running one instance of it.

**Comment by kfa1983** [comment]
Well, I guess I'm gonna have to quote you on this one... Oh geez, this is my fault, I'm an idiot. Closing... xD
