### ISSUE TITLE
haml rendering broken in node v0.1.96

### ISSUE THREAD

**Issue by danieldkim** [dantebronto/picard#9]
looks like the issue is that node is now passing a <code>Buffer</code> object to the <code>fs.readFile()</code> callback instead of a string.  here's the stack trace:

<pre>
/usr/local/src/picard/picard/lib/picard/haml.js:364
  var lines = text.split("\n"),
                   ^
TypeError: Object %div= partial('places/ul') has no method 'split'
    at Object.<anonymous> (/usr/local/src/picard/picard/lib/picard/haml.js:364:20)
    at Object.render (/usr/local/src/picard/picard/lib/picard/haml.js:434:25)
    at /usr/local/src/picard/picard/lib/picard/request_extensions.js:189:27
    at fs:81:13
    at node.js:204:9
</pre>

**Comment by danieldkim** [comment]
i have a fix for this issue in my fork:

http://github.com/danieldkim/picard/commit/292373daa1556ddba61a4e7e001c46c0cf1ac902

**Comment by danieldkim** [comment]
fixed committed to master: 3f255bf5023a9a3832bf9f5e8818ce938bce2d4f
